# Gitleaks Configuration for CoffeeOS
# Detect secrets and credentials in commits

title = "CoffeeOS Gitleaks Configuration"

[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)api[_-]?key[_-]?[=:]\s*['"]?([a-zA-Z0-9_\-]{32,})['"]?'''
tags = ["key", "api"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
tags = ["key", "openai"]

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[a-zA-Z0-9_-]*\.eyJ[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*'''
tags = ["token", "jwt"]

[[rules]]
id = "database-url"
description = "Database Connection String"
regex = '''(?i)(postgres|mysql|mongodb|redis)://[^\s]+'''
tags = ["database", "connection"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws[_-]?secret[_-]?access[_-]?key[_-]?[=:]\s*['"]?([a-zA-Z0-9/+=]{40})['"]?'''
tags = ["aws", "secret"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[a-zA-Z0-9]{36}'''
tags = ["github", "token"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
id = "twilio-api-key"
description = "Twilio API Key"
regex = '''SK[a-z0-9]{32}'''
tags = ["twilio", "key"]

[[rules]]
id = "stripe-key"
description = "Stripe API Key"
regex = '''(?i)(sk|pk)_(test|live)_[a-zA-Z0-9]{24,99}'''
tags = ["stripe", "key"]

[[rules]]
id = "mercado-pago-token"
description = "Mercado Pago Access Token"
regex = '''APP_USR-[0-9]{12,16}-[0-9]{6,8}-[a-z0-9]{32}'''
tags = ["mercadopago", "token"]

[allowlist]
description = "Global allowlist"
regexes = [
  '''(example|sample|test|mock|dummy|fake)''',
  '''YOUR_API_KEY_HERE''',
  '''<YOUR_API_KEY>''',
  '''xxx+''',
  '''yyy+''',
  '''zzz+'''
]
paths = [
  '''\.test\.ts$''',
  '''\.spec\.ts$''',
  '''\.mock\.ts$''',
  '''/tests?/''',
  '''/mocks?/''',
  '''/fixtures?/''',
  '''\.md$''',
  '''\.example$''',
  '''\.template$''',
  '''package-lock\.json$''',
  '''pnpm-lock\.yaml$''',
  '''yarn\.lock$'''
]
